#-------------------------------
# Site Settings
title: Sarah Moore, PhD
logo: # You can add own logo. For example '/images/logo.png'.
description: Forever a student. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Sarah Moore, PhD
  author__bio: Postdoctoral Fellow, Northwestern University
  author__avatar: '/images/01-1.jpg'

social:
- {icon: "ion-logo-github", link: "https://github.com/sarah-moore"}


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm Sarah Moore. 
  hero__description: <p align="justify"> I recently received my PhD in Political Science and MS in Statistics from Northwestern University. <br> <br>In my academic research, I develop mixed-methods research tools for the empirical study of comparative politics, especially where information is scarce or hard to reach. I substantively focus on the legacies of violent conflict, subnational governance and authority, and comparative political economy in Latin America. <br>

I am currently looking for new roles that allow me to use my problem-solving and multi-method technical expertise to solve complex, real-world challenges. </p>

  hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter



#-------------------------------
# Gallery Footer Section
#gallery:
 #gallery__title: Gallery
  #gallery__columns: 3
  #gallery__images:


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed