#-------------------------------
# Site Settings
title: Sarah Moore, PhD Candidate
logo: # You can add own logo. For example '/images/logo.png'.
description: Menca personal blogging theme for Jekyll
baseurl: "sarah-moore.github.io" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto 


#-------------------------------
# Author Settings
author:
  author__name: Sarah Moore
  author__bio: PhD Candidate in Political Science, M.S. Candidate in Statistics, Northwestern University
  author__avatar: '/images/01.jpg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/sarahmoreorless"}
- {icon: "ion-logo-github", link: "https://github.com/sarah-moore"}


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm Sarah Moore 
  hero__description: Change this
  hero__image: '/images/01.jpg'


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Rest'
      url: '/images/100.jpg'
    - alt: 'Lifestyle'
      url: '/images/101.jpg'
    - alt: 'Hobby'
      url: '/images/102.jpg'
    - alt: 'Notes'
      url: '/images/103.jpg'
    - alt: 'Rest'
      url: '/images/104.jpg'
    - alt: 'Hobby'
      url: '/images/105.jpg'
    - alt: 'Fashion'
      url: '/images/106.jpg'
    - alt: 'Notes'
      url: '/images/107.jpg'
    - alt: 'Rest'
      url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  email: sarahmoore2022@u.northwestern.edu # Add your email for contant form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed